name: "Bug Report"
description: Create a new ticket for a bug report
title: "[G<gruppe>] BUG: <title>"
labels: []
body:
  - type: dropdown
    id: group
    attributes:
      label: "Gruppe"
      description: Welche Gruppe?
      options:
        - G09
        - G10
        - G11
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "Was ist das Problem?"
      description: Was ist das Problem?
      placeholder: "Als User möchte ich ..."
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: "Was erwarte ich?"
      description: Was erwarte ich?
      placeholder: "Ich erwarte, dass ..."
    validations:
      required: false
  - type: textarea
    id: done
    attributes:
      label: "Definition of done"
      description: Definition of done
      placeholder: "- [ ] All tests passing\n- [ ] New tests added\n"
    validations:
      required: false
