json-accounts
secondAccountJson

	^ JsonObject new
		at: 'acct' put: 'petrapixelhuepfer';
		at: 'avatar'
			put: 'https://mastodon.de/system/accounts/avatars/116/800/000/000/000/002/original/51d4fbb60c8a1ef3.png';
		at: 'avatar_description' put: '';
		at: 'avatar_static'
			put: 'https://mastodon.de/system/accounts/avatars/116/800/000/000/000/002/original/51d4fbb60c8a1ef3.png';
		at: 'bot' put: false;
		at: 'created_at' put: '2026-02-14T15:17:00.000Z';
		at: 'discoverable' put: true;
		at: 'display_name' put: 'Petra Pixelhüpfer';
		at: 'emojis' put: #();
		at: 'fields' put: #();
		at: 'followers_count' put: 112;
		at: 'following_count' put: 91;
		at: 'group' put: false;
		at: 'header'
			put: 'https://mastodon.de/system/accounts/headers/116/800/000/000/000/002/original/c8a72f91d43b8a6d.png';
		at: 'header_description' put: '';
		at: 'header_static'
			put: 'https://mastodon.de/system/accounts/headers/116/800/000/000/000/002/original/c8a72f91d43b8a6d.png';
		at: 'hide_collections' put: nil;
		at: 'id' put: self secondAccountID;
		at: 'indexable' put: true;
		at: 'last_status_at' put: '2026-06-29';
		at: 'locked' put: false;
		at: 'noindex' put: false;
		at: 'note'
			put: '<p>Designerin mit einer Schwäche für schöne Icons und schlechte Wortspiele. Wenn etwas bunt blinkt, war ich wahrscheinlich beteiligt.</p>';
		at: 'roles' put: #();
		at: 'show_featured' put: true;
		at: 'show_media' put: true;
		at: 'show_media_replies' put: true;
		at: 'statuses_count' put: 742;
		at: 'uri' put: 'https://mastodon.de/users/petrapixelhuepfer';
		at: 'url' put: 'https://mastodon.de/@petrapixelhuepfer';
		at: 'username' put: 'petrapixelhuepfer';
		yourself