json-accounts
thirdAccountJson

	^ JsonObject new
		at: 'acct' put: 'rudirumpeltoot@chaos.social';
		at: 'avatar'
			put: 'https://chaos.social/system/accounts/avatars/117/100/000/000/000/003/original/96be7f54d20ab881.png';
		at: 'avatar_description' put: '';
		at: 'avatar_static'
			put: 'https://chaos.social/system/accounts/avatars/117/100/000/000/000/003/original/96be7f54d20ab881.png';
		at: 'bot' put: false;
		at: 'created_at' put: '2025-11-03T20:11:00.000Z';
		at: 'discoverable' put: true;
		at: 'display_name' put: 'Rudi Rumpeltoot';
		at: 'emojis' put: #();
		at: 'fields' put: #();
		at: 'followers_count' put: 57;
		at: 'following_count' put: 81;
		at: 'group' put: false;
		at: 'header'
			put: 'https://chaos.social/system/accounts/headers/117/100/000/000/000/003/original/f7ca1d882b4e55cf.png';
		at: 'header_description' put: '';
		at: 'header_static'
			put: 'https://chaos.social/system/accounts/headers/117/100/000/000/000/003/original/f7ca1d882b4e55cf.png';
		at: 'hide_collections' put: nil;
		at: 'id' put: self thirdAccountID;
		at: 'indexable' put: true;
		at: 'last_status_at' put: '2026-06-27';
		at: 'locked' put: false;
		at: 'noindex' put: false;
		at: 'note'
			put: '<p>Professioneller Bugfinder. Leider meistens in meinem eigenen Code. Begeistert von Smalltalk, Mäusen und viel zu langen Commit-Nachrichten.</p>';
		at: 'roles' put: #();
		at: 'show_featured' put: true;
		at: 'show_media' put: true;
		at: 'show_media_replies' put: true;
		at: 'statuses_count' put: 429;
		at: 'uri' put: 'https://chaos.social/users/rudirumpeltoot';
		at: 'url' put: 'https://chaos.social/@rudirumpeltoot';
		at: 'username' put: 'rudirumpeltoot';
		yourself