as yet unclassified
mockAccount
	^ '{
   "id":11792,
   "username":"momomo",
   "acct":"momomo",
   "display_name":"Test",
   "locked":true,
   "created_at":"2017-05-03T14:45:25.759Z",
   "followers_count":9,
   "following_count":323,
   "statuses_count":164,
   "note":"<p>Testdescription</p>",
   "url":"https://mastodon.land/@momomo",
   "avatar":"https://mastodon.land/system/accounts/avatars/000/011/792/original/e08f2f341bc79434.png?1500476588",
   "avatar_static":"https://mastodon.land/system/accounts/avatars/000/011/792/original/e08f2f341bc79434.png?1500476588",
   "header":"https://mastodon.land/system/accounts/headers/000/011/792/original/f626f17693f05599.png?1500476588",
   "header_static":"https://mastodon.land/system/accounts/headers/000/011/792/original/f626f17693f05599.png?1500476588"
}'