as yet unclassified
mockSearch
	^ '{
   "accounts":[
      {
         "id":11798,
         "username":"schmidtflo",
         "acct":"schmidtflo@mastodon.network",
         "display_name":"Florian Schmidt",
         "locked":false,
         "created_at":"2017-05-03T15:18:29.300Z",
         "followers_count":1,
         "following_count":1,
         "statuses_count":7,
         "note":"",
         "url":"https://mastodon.network/@schmidtflo",
         "avatar":"https://mastodon.land/system/accounts/avatars/000/011/798/original/missing.png?1493824709",
         "avatar_static":"https://mastodon.land/system/accounts/avatars/000/011/798/original/missing.png?1493824709",
         "header":"https://mastodon.land/system/accounts/headers/000/011/798/original/missing.png?1493824710",
         "header_static":"https://mastodon.land/system/accounts/headers/000/011/798/original/missing.png?1493824710"
      }
   ],
   "statuses":[

   ],
   "hashtags":[

   ]
}'